-   id: nglint
    name: nglint
    description: Runs ng lint
    entry: nglint.py
    language: script
    # NOTE: we don't need filenames, we simply lint what is defined in project's directory
    pass_filenames: false

    # Use additional_dependencies to install the actual node package
    minimum_pre_commit_version: 0.12.0
